name: Gestao de Vagas Application



on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' 
      
      - name: Build project
        run: mvn clean install -DskipTests
      
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t srmatheusmaciel/gestao_vagas .
      
      - name: Push Docker image
        run: docker push srmatheusmaciel/gestao_vagas

  deploy: 
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker hub image
        run: docker pull srmatheusmaciel/gestao_vagas:latest

      - name: remove container
        run: docker rm -f gestao-vagas

      - name: Run Docker container gestao-vagas
        run: docker run -d -p 8080:8080 -e DATABASE_URL=${{secrets.DATABASE_URL}} -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} --name gestao-vagas srmatheusmaciel/gestao_vagas